add success state
jcaiqueoliveira/finger-burn pull request #7
Opened 2018-03-16 20:59 UTC by jcaiqueoliveira

add success state 
add test end to end

2018-03-17 00:08 UTC, ubiratansoares requested changes
A partir da próxima semana, qualquer PR que envolver mais de que 

- 20 arquivos
- 400 linhas de alterações

 (esses números não são definitivos)

precisará de uma descrição no corpo do PR que documente as alterações feitas e facilite a revisão do leitor.

2018-03-19 14:48 UTC, ubiratansoares requested changes
Fiz comentários

2018-03-19 14:48 UTC, ubiratansoares commented on app/src/androidTest/java/sample/kanda/burn/fact/states/SuccessStateTest.kt
> +        scheduler.advanceTimeBy(1000, TimeUnit.MILLISECONDS)
Pq precisa disso aqui?

2018-03-19 14:48 UTC, ubiratansoares commented on app/src/androidTest/java/sample/kanda/burn/fact/states/SuccessStateTest.kt
> +        mockServer.shutdown()
Algum motivo para start/shutdown não serem executados em before / tearDown ?

2018-03-19 14:48 UTC, ubiratansoares commented on app/src/androidTest/java/sample/kanda/burn/fact/states/SuccessStateTest.kt
> +class SuccessStateTest : ActivityRule<FactActivity>(FactActivity::class.java) {
Pq esse teste está separado do teste que verifica o estado de loading?

2018-03-19 14:48 UTC, ubiratansoares commented on app/src/androidTest/java/sample/kanda/burn/fact/states/SuccessStateTest.kt
> +        val service = configureService(mockServer.url("/").toString())
Existe uma maneira melhor de sobreescrever a dependência da API com mockWebServer sem ser assim?

Pq não trocar apenas a instância da URL em tempo de teste?

2018-03-19 14:48 UTC, ubiratansoares commented on app/src/main/java/sample/kanda/burn/Injector.kt
> +            FactNavigator(Schedulers.computation())
Não entendi esse Scheduler aqui

2018-03-19 14:53 UTC, jcaiqueoliveira commented on app/src/androidTest/java/sample/kanda/burn/fact/states/SuccessStateTest.kt
> +class SuccessStateTest : ActivityRule<FactActivity>(FactActivity::class.java) {
Achei que ficaria mais organizado separar os testes pelos estados

2018-03-19 15:03 UTC, jcaiqueoliveira commented on app/src/main/java/sample/kanda/burn/Injector.kt
> +            FactNavigator(Schedulers.computation())
A scheduler como parametro serve para permitir a troca na execução do teste.
Para execução do debounce eu estou fazendo uso da Scheduler computation. Quando faço teste eu uso TestScheduler pois com ela tenho controle sobre o tempo e consigo fazer algo como: scheduler.advanceTimeBy(1000, TimeUnit.MILLISECONDS).

2018-03-19 15:16 UTC, jcaiqueoliveira commented on app/src/androidTest/java/sample/kanda/burn/fact/states/SuccessStateTest.kt
> +        scheduler.advanceTimeBy(1000, TimeUnit.MILLISECONDS)
Sim, é o tempo do debounce, o que estou fazendo é avançar para o fim desse tempo. Só depois de avançar o tempo que consigo continuar com as checagens do robot.
Quando digo "só depois de avançar o tempo" é referente a escolha feita em usar TestScheduler para esse teste.

2018-03-19 15:36 UTC, ubiratansoares commented on app/src/main/java/sample/kanda/burn/Injector.kt
> +            FactNavigator(Schedulers.computation())
OK. O problema é que esse Navigator não usa esse Scheduler pra nada, mas apenas para instanciar outro objeto `WaitingInputState`. Pq esse último não poderia vir instanciado?

2018-03-19 15:43 UTC, ubiratansoares commented on app/src/androidTest/java/sample/kanda/burn/fact/states/SuccessStateTest.kt
> +class SuccessStateTest : ActivityRule<FactActivity>(FactActivity::class.java) {
Um teste funcional de aceitação deve ser (pseudo código)

Dado : <a tela inicia a partir de um termo válido>
Então
(a) Carregamos o termo
(b) Mostramos os resultados com sucesso
(c1) Nenhuma condição de erro é apresentada
(c2) A tela não está mais carregando

Esse cenário configura 1 (UM) teste funcional de aceitação. Ele deve ser bom o suficiente para que alguém de QA ou de produto possa ler o que acontece nele em alto nível e entender o que se passa sem se preocupar com detalhes de baixo nível

https://github.com/ubiratansoares/uol-challenge/blob/master/app/src/androidTestMock/java/br/ufs/uolchallenge/NewsFeedAcceptanceTests.kt

Repare como no teste acima o mecanismo de test robots isola completamente`QUAIS` condições eu estou verificando do `COMO` eu estou verificando. E todas as condições são verificadas, garantindo a consistência visual da UI.

Um teste E2E implicaria testar tanto a tela de capturar o termo de busca quando mostrar os resultados em si.

Ou seja : por definição, esse seu teste não é E2E, e como um teste funcional de aceitação, ele está semanticamente errado.

2018-03-19 15:44 UTC, ubiratansoares commented on app/src/androidTest/java/sample/kanda/burn/fact/states/SuccessStateTest.kt
> +        scheduler.advanceTimeBy(1000, TimeUnit.MILLISECONDS)
Se alguém mudar a constante de tempo na classe, diminuindo o tempo de debounce para 500ms, o que acontece com esse teste?

2018-03-19 16:45 UTC, jcaiqueoliveira commented on app/src/main/java/sample/kanda/burn/Injector.kt
> +            FactNavigator(Schedulers.computation())
Então, optei por só criar quando necessário pois caso eu não entre num estado de sucesso vou criar uma instancia de forma desnecessária.

2018-03-19 17:23 UTC, ubiratansoares commented on app/src/main/java/sample/kanda/burn/Injector.kt
> +            FactNavigator(Schedulers.computation())
O grande problema aqui é que existe um problema na modelagem das abstrações de FactNavigator.

Por um lado, FactNavigator poderia receber `WaitingInputState` como colaborador via DI - conforme proposto acima ; por outro lado, `WaitingInputState` depende de FactsNavigator, o que obviamente inviabiliza o fornecimento dessa instância via DI por motivos de dependência cíclica ...

2018-03-19 19:54 UTC, ubiratansoares approved these changes

2018-03-19 20:34 UTC, merged